name: Image Build and Push

on:
  workflow_call:
    inputs:
      gh_username:
        description: GitHub username (lowercase)
        required: true
        type: string
      gh_token:
        description: GitHub token for authentication
        required: true
        type: string
      image_name:
        description: Name of the Docker image to build and push
        required: true
        type: string
      git_ref:
        description: Git ref to check out
        required: true
        type: string
      pr_number:
        description: Pull request number (if applicable)
        required: false
        type: string
      context:
        description: Build context for the Dockerfile
        required: true
        type: string
      dockerfile:
        description: Path to the Dockerfile
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}

      - name: Set variables
        shell: bash
        run: |
          echo "SHA=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "IMAGE_REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${{ inputs.git_ref }}" >> $GITHUB_ENV
          if [[ "${{ inputs.pr_number }}" != '' ]]; then
            git fetch origin ${{ inputs.git_ref }}
            echo "SHA=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "IMAGE_REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV
            echo "IMAGE_VERSION=pr-${{ inputs.pr_number }}" >> $GITHUB_ENV
          fi

      - name: Parse Input Values
        shell: bash
        run: |
          echo "GH_USERNAME=$(tr '[:upper:]' '[:lower:]' <<< '${{ inputs.github_username }}')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GH_USERNAME }}
          password: ${{ inputs.gh_token }}

      - name: Prepare Container Metadata tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ inputs.gh_username }}/${{ inputs.image_name }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION }}
            type=raw,value=${{ env.SHA }}
          labels: |
            org.opencontainers.image.revision=${{ env.IMAGE_REVISION }}
            org.opencontainers.image.version=${{ env.IMAGE_VERSION }}

      - name: Build and Push to Container Registry
        id: builder
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Inspect Docker Image
        shell: bash
        run: |
          docker image inspect ghcr.io/${{ inputs.gh_username }}/${{ inputs.image_name }}:latest
          docker image inspect ghcr.io/${{ inputs.gh_username }}/${{ inputs.image_name }}:${{ env.SHA }}
          docker image inspect ghcr.io/${{ inputs.gh_username }}/${{ inputs.image_name }}:${{ env.IMAGE_VERSION }}
