name: App Build Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - app/**
      - frontend/**
      - .github/workflows/app_build_image.yaml
      - .github/workflows/app_deploy_image.yaml
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - app/**
      - frontend/**
      - .github/workflows/app_build_image.yaml
      - .github/workflows/app_deploy_image.yaml
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      GIT_REF: ${{ github.event_name == 'pull_request' && format('refs/pull/{0}/head', github.event.pull_request.number) || github.ref_name }}

    steps:
      - name: Checkout code to get actions
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}

      - name: Call Image Build and Push Composite Action
        uses: ./.github/actions/image_build_and_push
        with:
          gh_username: ${{ github.repository_owner }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          image_name: event-stream-service-app
          git_ref: ${{ env.GIT_REF }}
          pr_number: ${{ github.event.pull_request.number || '' }}
          context: .
          dockerfile: ./Dockerfile
