name: App Deploy Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev, test, prod)"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
      git_ref:
        description: "Git reference (branch or commit SHA) to deploy"
        required: false
        default: main
      pr_number:
        description: "Pull request number (if applicable)"
        required: false
        default: ""

  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to (dev, test, prod)"
        required: true
        type: string
      git_ref:
        description: "Git reference (branch or commit SHA) to deploy"
        required: false
        default: main
      pr_number:
        description: "Pull request number (if applicable)"
        required: false
        default: ""

jobs:
  deploy:
    name: Deploy Event Stream Service App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}

      - name: Set IMAGE_VERSION
        shell: bash
        run: |
          echo "IMAGE_VERSION=${{ inputs.git_ref }}" >> $GITHUB_ENV
          if [[ "${{ inputs.pr_number }}" != '' ]]; then
            echo "IMAGE_VERSION=pr-${{ inputs.pr_number }}" >> $GITHUB_ENV
          fi

      - name: Deploy Helm Chart
        uses: ./.github/actions/deploy_helm_chart
        with:
          chart_path: ./charts/event-stream-service-app
          values_file: charts/event-stream-service-app/values-${{ inputs.environment }}.yaml
          overrides: image.tag=${{ env.IMAGE_VERSION }}
          release_name: event-stream-service-app
          server: ${{ secrets.OPENSHIFT_SERVER }}
          token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ vars.NAMESPACE }}
