name: App Deploy Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev, test, prod)"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
      git_ref:
        description: "Git reference (branch or commit SHA) to deploy"
        required: false
        default: main
        type: string
      pr_number:
        description: "Pull request number (if applicable)"
        required: false
        default: ""
        type: string

  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to (dev, test, prod)"
        required: true
        type: string
      git_ref:
        description: "Git reference (branch or commit SHA) to deploy"
        required: false
        default: main
        type: string
      pr_number:
        description: "Pull request number (if applicable)"
        required: false
        default: ""
        type: string

jobs:
  deploy:
    name: Deploy Event Stream Service App
    runs-on: ubuntu-latest

    env:
      GIT_REF: ${{ inputs.pr_number && format('refs/pull/{0}/head', inputs.pr_number) || inputs.git_ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}

      - name: Set IMAGE_VERSION and RELEASE/ROUTE overrides
        id: dyn
        shell: bash
        run: |
          echo "IMAGE_VERSION=${{ inputs.git_ref }}" >> $GITHUB_ENV
          echo "RELEASE_NAME=event-stream-service-app" >> $GITHUB_ENV
          echo "ROUTE_OVERRIDE=" >> $GITHUB_ENV
          if [[ "${{ inputs.pr_number }}" != '' ]]; then
            echo "IMAGE_VERSION=pr-${{ inputs.pr_number }}" >> $GITHUB_ENV
            echo "RELEASE_NAME=event-stream-service-app-pr-${{ inputs.pr_number }}" >> $GITHUB_ENV
            echo "ROUTE_OVERRIDE=route.host=ess-app-pr-${{ inputs.pr_number }}.apps.silver.devops.gov.bc.ca" >> $GITHUB_ENV
          fi

      - name: Deploy Helm Chart
        uses: ./.github/actions/deploy_helm_chart
        with:
          chart_path: ./charts/event-stream-service-app
          values_file: charts/event-stream-service-app/values-${{ inputs.environment }}.yaml
          overrides: |
            image.tag=${{ env.IMAGE_VERSION }}${{ env.ROUTE_OVERRIDE && format(',{0}', env.ROUTE_OVERRIDE) || '' }}
          release_name: ${{ env.RELEASE_NAME }}
          server: ${{ secrets.OPENSHIFT_SERVER }}
          token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ vars.NAMESPACE }}
